# Generated by Django 3.2.2 on 2021-05-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='intentsity',
            new_name='intensity',
        ),
    ]
